<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<style>
.flash-modal{position:fixed;inset:0;z-index:3000;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(5,30,27,.48);backdrop-filter:blur(3px)}.flash-dialog{width:min(420px,100%);overflow:hidden;border-radius:18px;background:#fff;box-shadow:0 24px 70px rgba(0,0,0,.28);animation:flash-pop .22s ease}.flash-banner{height:7px;background:#138a78}.flash-modal.error .flash-banner{background:#d64553}.flash-modal.warning .flash-banner{background:#df9200}.flash-content{padding:26px;text-align:center}.flash-symbol{display:grid;place-items:center;width:54px;height:54px;margin:0 auto 14px;border-radius:50%;background:#e5f8f3;color:#087a69;font-size:27px;font-weight:800}.flash-modal.error .flash-symbol{background:#fff0f1;color:#c93445}.flash-modal.warning .flash-symbol{background:#fff5df;color:#bf7800}.flash-content h3{margin:0 0 9px;color:#073e37;font-size:20px}.flash-content p{margin:0;color:#456560;line-height:1.55}.flash-close{width:100%;margin-top:22px;border:0;border-radius:10px;padding:12px 16px;background:#087b6a;color:#fff;font-weight:700;cursor:pointer}.flash-modal.error .flash-close{background:#c93445}.flash-modal.warning .flash-close{background:#bd7907}@keyframes flash-pop{from{opacity:0;transform:scale(.94) translateY(10px)}to{opacity:1;transform:none}}
</style>
<c:if test="${not empty sessionScope.flashSuccess}"><div class="flash-modal success" role="alertdialog"><div class="flash-dialog"><div class="flash-banner"></div><div class="flash-content"><div class="flash-symbol">✓</div><h3>Thành công</h3><p><c:out value="${sessionScope.flashSuccess}"/></p><button class="flash-close">Đã hiểu</button></div></div></div><c:remove var="flashSuccess" scope="session"/></c:if>
<c:if test="${not empty sessionScope.flashWarning}"><div class="flash-modal warning" role="alertdialog"><div class="flash-dialog"><div class="flash-banner"></div><div class="flash-content"><div class="flash-symbol">!</div><h3>Cảnh báo</h3><p><c:out value="${sessionScope.flashWarning}"/></p><button class="flash-close">Đã hiểu</button></div></div></div><c:remove var="flashWarning" scope="session"/></c:if>
<c:if test="${not empty sessionScope.flashError or not empty requestScope.error}"><div class="flash-modal error" role="alertdialog"><div class="flash-dialog"><div class="flash-banner"></div><div class="flash-content"><div class="flash-symbol">×</div><h3>Không thể thực hiện</h3><p><c:out value="${not empty sessionScope.flashError ? sessionScope.flashError : requestScope.error}"/></p><button class="flash-close">Đóng</button></div></div></div><c:remove var="flashError" scope="session"/></c:if>
<script>document.querySelectorAll('.flash-modal').forEach(m=>{m.querySelector('.flash-close').addEventListener('click',()=>m.remove());m.addEventListener('click',e=>{if(e.target===m)m.remove()})});</script>
